app1/urls.py
from django.urls import path
from . import views

app_name = 'app1'

urlpatterns = [
    path('',views.main_page,name='mainpage'),
    path('login',views.login,name='login'),
    path('owner_home',views.owner_home,name='owner_home'),
    path('add_medicine',views.add_medicine,name='add_medicine'),
    path('view_medicine',views.view_medicine,name='view'),
 ]

truepharmacy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1.urls')),
    
]+static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

app1/models.py
from email.policy import default
from django.db import models


# Create your models here.

# class Owner(models.Model):
#     owner_id = models.AutoField(primary_key=True,default="")
#     owner_email = models.CharField(max_length=50)
#     owner_password = models.CharField(max_length=10)
    
    

#     class Meta:
#         db_table = "owner"

class Medicine(models.Model):
    
    medicine_name = models.CharField(max_length=50)
    medicine_quantity = models.CharField(max_length=100)
    medicine_price = models.CharField(max_length=100)
    purchace_price = models.CharField(max_length=100,default=0)
    selling_cost = models.CharField(max_length=100,default=0)
    medicine_image = models.ImageField(upload_to = 'medicine/')
    
   

    class Meta:
        db_table = "medicine"


class Owner(models.Model):
    owner_id = models.AutoField(primary_key=True)
    owner_email = models.CharField(max_length=50)
    owner_password = models.CharField(max_length=10)

    class Meta:
        db_table = "owner"

class Bill(models.Model):
    bill_id = models.AutoField(primary_key=True)
    medicine = models.ForeignKey(Medicine, on_delete=models.CASCADE)
    qty = models.IntegerField()

    class Meta:
        db_table = 'bill'

app1/views.py
from django.shortcuts import redirect, render
from app1.models import Medicine, Owner

# Create your views here.
def main_page(request):
    return render(request,'mainpage.html')

def login(request):
    msg = ''
    if request.method == 'POST':
        owner_email = request.POST['owner_email']
        owner_password = request.POST['owner_password']

        owner_exist = Owner.objects.filter(owner_email = owner_email,owner_password = owner_password)

        if owner_exist:
            owner_data = Owner.objects.get(owner_email = owner_email,owner_password = owner_password)
            request.session['owner'] = owner_data.owner_id
            return redirect('app1:owner_home')
        else:
            msg = 'Unknown Owner..!'
    return render(request,'login.html',{'msg':msg})

def owner_home(request):
    return render(request,'owner_home.html')

def add_medicine(request):
    msg =""
    if request.method == 'POST':
        name = request.POST['medicine_name']
        quantity = request.POST['medicine_quantity']
        price = request.POST['medicine_price']
        selling_cost = request.POST['selling_cost']
        purchace_price = request.POST['purchace_price']
        image = request.FILES['pimg']
        print(image)
        new_images = Medicine(medicine_image = image,medicine_name=name,medicine_quantity=quantity,medicine_price=price,purchace_price=purchace_price,selling_cost=selling_cost)
        new_images.save()

        msg = "added"
    return render(request,'add_medicine.html',{'msg':msg,})

def view_medicine(request):
    medicine = Medicine.objects.all()

    return render(request,'view_medicine.html',{'medicine':medicine,})
    
def billing(request):
    medicine = Medicine.objects.all()

    if request.method == 'POST':
        mid = request.POST['medicine']
        qty = request.POST['qty']
        medicineqty = Medicine.objects.get(id=mid)

        medicineqty.quantity = medicineqty.quantity - int(qty)
        medicineqty.save()
        return render(request,'bill.html',{'medicine':medicine,})

        
    return render(request,'bill.html',{'medicine':medicine,})

app1/templates/add_medicine.html
{% extends 'master.html' %}
    {% block content %}
    <section class="page1"> 
    
        <div class="form">
        <p>Add Medicine</p>
        <form action="" method="POST"  enctype="multipart/form-data">
        {% csrf_token %}
    <input type="text" name="medicine_name" placeholder="Name of Medicine">
    <input type="text" name="medicine_quantity" placeholder="Quantity">
    <input type="text" name="medicine_price" placeholder="medicine_price">
    <input type="text" name="purchace_price" placeholder="purchace_price">
    <input type="text" name="selling_cost" placeholder="selling_cost">
    <label for="">Upload Image :</label>
    <input type="file" name="pimg"><br><br>

    <button>Add</button>

    
    
        </form>
        {{msg}}
    </section> 
{% endblock %}

app1/templates/bill.html
{% extends 'master.html' %}
    {% block content %}
    {% load static %}
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
    crossorigin="anonymous"></script>
<div class="container">
    <div class="pt-5 pb-5">
        <div class="formbill">
            <form method="POST">
                {% csrf_token %}
        
        
        
                <h1
                    style="font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif; font-weight: bolder; margin-bottom: 40px;">
                    PHARMA BILLING</h1>
                <label>Customer Name:</label><input type="text" style="margin-right: 250px;">
                <label>Phone number:</label><input type="number">
                <label style="margin-left: 660px; margin-top: 20px;">date:</label><input type="datetime">
        
                <table class="table" style="margin-top: 20px;">
                    <tr>
                        <th>Sl no</th>
                        <th>Medicine Name</th>
                        <th>Quantity</th>
                        <th>Price</th>
                        <th>Item Total</th>
                    </tr>
                    <tr>
                        <th>1</th>
                        <td>
                            <select name="medicine" id="medicine">
                            {% for m in medicine %}
                                <option value="{{m.id}}" id="mname">{{m.name}}</option>
                            {% endfor %}
                            </select>
                        </td>
                        <td>
                            <input type="number" min="1" max="{{m.quantity}}" id="qty" name="qty">
                        </td>
                        <td>
        
                            <input type="number"  name="price" id="price">
                        </td>
                        <td><input type="number" readonly name="total" id="total"></td>
                    </tr>
        
                </table>
                <table style="float: right;">
                    <tr>
                        <td>GST:</td>
                        <td><input type="text" id="gst">
                        </td>
                    </tr>
                    <tr>
                        <td>Grand Total:
                        <td><input type="text" id="gtotal"></td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <div class="d-grid gap-2 col-6 mx-auto" style="margin-top: 20px;">
                                <button class="btn btn-primary" type="submit">GENERATE</button>
                            </div>
                        </td>
                    </tr>
                </table>
        
            </form>
        
            
        </div></div>
        
        <script>
            $(document).ready(function () {
                $('#medicine'). change(function () {
                    // console.log('test')
                    $.ajax({
                        url: 'http://127.0.0.1:8000/price',
                        data: {
                            'id': $(this).val()
                        },
                        type: 'get',
                        success: function (response) {
                            // alert(response);
                            // $('#price').html(response)
                            var price = Number(response)
                            $('#price').val(price)
                            // document.getElementById('price').value=response;
                        }
                    })
                })
            })
        
            $(document).ready(function (){
                $('#qty').change(function (){
                    $.ajax({
                        url: 'http://127.0.0.1:8000/total',
                        data: {
                            'qty': $(this).val() ,
                            'price': $('#price').val()
        
                        },
                        type: 'get',
                        success: function (response) {
                           var total = Number(response)
                           $('#total').val(total)
                        }
                    })
                    // alert(Number($('#price').val()) * Number($('qty').val()))
                    // total=Number($('#price').val()) * Number($('qty').val())
                    // $('#total').val(total)
                })
        
            })
        
        
            $(document).ready(function (){
                $('#qty').change(function (){
                    $.ajax({
                        url: 'http://127.0.0.1:8000/gst',
                        data: {
                            'id': $('#medicine').val() ,
                            'qty': $('#qty').val() ,
        
                        },
                        type: 'get',
                        success: function (response) {
                           var gst = Number(response)
                           $('#gst').val(gst)
                        }
                    })
                    
                })
        
            })
        
            $(document).ready(function (){
                $('#qty').change(function (){
                    $.ajax({
                        url: 'http://127.0.0.1:8000/grandtotal',
                        data: {
                            'id': $('#medicine').val() ,
                            'qty': $('#qty').val() ,
        
                        },
                        type: 'get',
                        success: function (response) {
                           var gtotal = Number(response)
                           $('#gtotal').val(gtotal)
                        }
                    })
                    
                })
        
            })
        
        
        
        </script>

{% endblock %}

app1/templates/login.html
{% extends 'master.html' %}
    {% block content %}

<section class="page1"> 
    
    <div class="form">
    <p>Login</p>
    <form action="" method="POST">
    {% csrf_token %}
<input type="email" name="owner_email" id="user_email" placeholder="Email Address">
<span id="un1"></span>
<input type="password" name="owner_password" id="pw" placeholder="Password">
<span id="pw1"></span>
<button>Login</button>


    </form>
    {{msg}}
</section> 

{% endblock %}

app1/templates/mainpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="/static/css/mainpage.css" rel="stylesheet">
</head>
<body>
    {% extends 'master.html' %}
    {% block content %}
    <section class="section1">
        <div class="container">
            <br/><br/>
            <p class="unlimited pt-5">Retail Pharmacy Management<br>Software with Pharmacy Billing</p>
            <div class="pb-5">
            <a class="btn btn-outline-primary" type="submit" href="{% url 'app1:login' %}">Get Started</a>
            <br/><br/>
            </div>
        </div>
    </section>
    {% endblock %}
</body>
</html>

app1/templates/master.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

<!-- css link -->
<link href="/static/css/mainpage.css" rel="stylesheet">
<link href="/static/css/login.css" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">TruePharmacy</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
              </li>
            </ul>
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>

      {% block content %}
      {% endblock %}

      <!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted">
    <!-- Section: Social media -->
    <section
      class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom"
    >
      <!-- Left -->
      <div class="me-5 d-none d-lg-block">
        <span>Get connected with us on social networks:</span>
      </div>
      <!-- Left -->
  
      <!-- Right -->
      <div>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-twitter"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-google"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-instagram"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-linkedin"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-github"></i>
        </a>
      </div>
      <!-- Right -->
    </section>
    <!-- Section: Social media -->
  
    <!-- Section: Links  -->
    <section class="">
      <div class="container text-center text-md-start mt-5">
        <!-- Grid row -->
        <div class="row mt-3">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <!-- Content -->
            <h6 class="text-uppercase fw-bold mb-4">
              <i class="fas fa-gem me-3"></i>Company name
            </h6>
            <p>
              Here you can use rows and columns to organize your footer content. Lorem ipsum
              dolor sit amet, consectetur adipisicing elit.
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Products
            </h6>
            <p>
              <a href="#!" class="text-reset">Angular</a>
            </p>
            <p>
              <a href="#!" class="text-reset">React</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Vue</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Laravel</a>
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Useful links
            </h6>
            <p>
              <a href="#!" class="text-reset">Pricing</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Settings</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Orders</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Help</a>
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Contact
            </h6>
            <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
            <p>
              <i class="fas fa-envelope me-3"></i>
              info@example.com
            </p>
            <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
            <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
          </div>
          <!-- Grid column -->
        </div>
        <!-- Grid row -->
      </div>
    </section>
    <!-- Section: Links  -->
  
    <!-- Copyright -->
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
      © 2021 Copyright:
      <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->
</body>
</html>

app1/templates/owner_home.html
{% extends 'master.html' %}
    {% block content %}
<div class="container">
    <div class="pt-5 pb-5">
    <h4>Add Medicine</h4>
    <a href="{% url 'app1:add_medicine' %}" class="btn btn-primary">Click here</a>
    </div>
    <h4>view Medicine</h4>
    <a href="{% url 'app1:view' %}" class="btn btn-primary">Click here</a>
</div>
{% endblock %}

app1/templates/view_medicine.html
{% extends 'master.html' %}
    {% block content %}
    <section class="page1"> 
    

        <div class="row">
            <div class="col-lg-12">

                <table class="table">

                    <thead>
                        <tr>
                            <th scop="col">medicine id</th>
                            <th scop="col">medicine name</th>
                            <th scop="col">Prdoduct image</th>
                            <th scop="col">Price</th>
                            {% comment %} <th>Description</th> {% endcomment %}
                            <th scop="col">Stock Availability</th>
                            <th scop="col">medicine purchase price</th>
                            <th scop="col">medicine selling cost</th>
                        
                        </tr>
                    </thead>
                     {% for i in medicine %}
                   <tbody>
                    <tr>
                        
                       <th scop="row">{{i.id}}</th>
                       <td>{{i.medicine_name | upper }}</td>
                       <td> <img src="{{i.medicine_image.url}}" alt="fdghfgh" width="250px"></td>
                       <td>{{i.quantity}}</td>
                       <td>{{i.purchace_price}}</td>
                       <td>{{i.selling_cost}}</td>

                    </tr>
                   </tbody> 
                    {% endfor %}
                </table>

            </div>

        </div>
        
        
    </section> 
{% endblock %}